load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "problem_statement",
    srcs = [
        "anagram.cpp",
        "calculator.cpp",
        "find_max_rides.cpp",
        "find_right_sibling.cpp",
        # "invalid_transactions.cpp",
        # "find_team_players.cpp",
        "asteroid_collision.cpp",
        "path_with_max_probability.cpp",
        "two_city_scheduling.cpp",
    ],
    hdrs = [
        "is_prime.h",
        "anagram.h",
        "calculator.h",
        "distance_between_nodes.h",
        "find_max_rides.h",
        "find_right_sibling.h",
        "image.h",
        "insert_sorted.h",
        # "find_team_players.h",
        "asteroid_collision.h",
        # "invalid_transactions.h",
        "path_with_max_probability.h",
        "shared_ptr.h",
        "tallest_billboard.h",
        "two_city_scheduling.h",
    ],
    visibility = ["//visibility:public"],
)
