load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "problem_statement",
    srcs = [
        "anagram.cpp",
        "calculator.cpp",
        "find_max_rides.cpp",
        "find_right_sibling.cpp",
    ],
    hdrs = [
        "anagram.h",
        "calculator.h",
        "find_max_rides.h",
        "find_right_sibling.h",
        "insert_sorted.h",
        "shared_ptr.h",
    ],
    visibility = ["//visibility:public"],
)
