cc_library(
    name = "tree",
    srcs = [
        "expression_tree.cpp",
        "trie.cpp",
    ],
    hdrs = [
        "binary_tree.h",
        "expression_tree.h",
        "max_heap.h",
        "node.h",
        "trie.h",
    ],
    visibility = ["//visibility:public"],
)
