load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "graph",
    srcs = [
        # "astar.h",
        # "breadth_first_search.h",
        # "dijkstra.h",
        "depth_first_search.hpp",
        "graph.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@nholthaus//:units",
    ],
)
