cc_test(
    name = "unit_tests",
    srcs = [
        "postfix_expression_tests.cpp",
        "unique_character_string_tests.cpp",
    ],
    deps = [
        "//algorithms/string",
        "@googletest//:gtest_main",
    ],
)
