cc_test(
    name = "unit_tests",
    srcs = [
        "expression_tree_tests.cpp",
        "max_heap_tests.cpp",
    ],
    deps = [
        "//algorithms/tree",
        "@googletest//:gtest_main",
    ],
)
