load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "find_right_sibling_tests",
    srcs = ["find_right_sibling_tests.cpp"],
    deps = [
        "//argoai:find_right_sibling",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "find_max_rides_tests",
    srcs = ["find_max_rides_tests.cpp"],
    deps = [
        "//argoai:find_max_rides",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "calculator_tests",
    srcs = ["calculator_tests.cpp"],
    deps = [
        "//argoai:calculator",
        "@googletest//:gtest_main",
    ],
)
