load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "unit_tests",
    srcs = [
        "anagram_tests.cpp",
        "calculator_tests.cpp",
        "distance_between_nodes_tests.cpp",
        "find_max_rides_tests.cpp",
        "find_right_sibling_tests.cpp",
        "image_tests.cpp",
        "insert_sorted_tests.cpp",
        "count_character_tests.cpp",
        "is_prime_tests.cpp",
        "find_kth_max_element_tests.cpp",
        # "find_team_players_tests.cpp",
        "asteroid_collision_tests.cpp",
        # "invalid_transactions_tests.cpp",
        "path_with_max_probability_tests.cpp",
        "tallest_billboard_tests.cpp",
        "two_city_scheduling_tests.cpp",
    ],
    deps = [
        "//problem_statement",
        "@googletest//:gtest_main",
    ],
)
