load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "find_right_sibling",
    srcs = ["find_right_sibling.cpp"],
    hdrs = ["find_right_sibling.h"],
)

cc_library(
    name = "find_max_rides",
    srcs = ["find_max_rides.cpp"],
    hdrs = ["find_max_rides.h"],
)

cc_library(
    name = "calculator",
    srcs = ["calculator.cpp"],
    hdrs = ["calculator.h"],
)
